---

- hosts: all
  become: true
  pre_tasks:

  - name : install updates (CentOS)
    tags: always
    dnf:
      update_only: yes
      update_cache: yes
    when: ansible_distribution in ["CentOS"]

  - name : install updates (Ubuntu)
    tags: always
    apt:
      upgrade: dist
      update_cache: yes
    when: ansible_distribution in ["Ubuntu"]  


- hosts: all
  become: true
  tasks:

  - name: add ssh key for philbot
    tags: always
    authorized_key:
      user: philbot
      key: "ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIOKNfldT/qKQzgZnE94pU0Gh0r+IUFerszq0uS2vv81L philbot"

- hosts: web_servers
  become: true
  tasks:

  - name: install unzip
    package:
      name: unzip

  - name: install terraform
    unarchive:
      src: https://releases.hashicorp.com/terraform/1.1.2/terraform_1.1.2_linux_amd64.zip
      dest: /usr/local/bin
      remote_src: yes
      mode: 0755
      owner: root
      group: root

- hosts: web_servers
  become: true
  tasks:

  - name: install apache2 and php package for Debian
    tags: apache,apache2,ubuntu
    apt:
      name:
        - apache2
        - libapache2-mod-php
      state: latest
    when: ansible_distribution in ["Ubuntu", "Debian"]

  - name: install httpd and php package for CentOS
    tags: apache,httpd,centos
    dnf:
      name: 
        - httpd
        - php
      state: latest
    when: ansible_distribution in ["CentOS"]

  - name: start httpd (CentOS)
    tags: apache,centos,httpd
    service:
      name: httpd
      state: started
      enabled: yes
    when: ansible_distribution in ["CentOS"]

  - name: change e-mail address for admin
    tags: apache,centos,httpd
    lineinfile:
      path: /etc/httpd/conf/httpd.conf
      regexp: '^ServerAdmin'
      line: ServerAdmin somebody@email.example.com
    when: ansible_distribution in ["CentOS"]
    register: httpd
  
  - name: FirewallD rules
    firewalld:
      permanent: yes
      immediate: yes
      service: "{{ item }}"
      state: enabled
    with_items:
      - http
      - https
    when: ansible_distribution in ["CentOS"]

  - name: restart httpd (CentOS)
    tags: apache,centos,httpd
    service:
      name: httpd
      state: restarted
    when: httpd.changed

  - name: copy default html to site
    tags: apache,apache2,httpd
    copy:
      src: default_site.html
      dest: /var/www/html/index.html
      owner: root
      group: root
      mode: 0644

- hosts: db_servers
  become: true
  tasks:

  - name: install mariadb Package (Debian)
    tags: mariadb,ubuntu,db
    apt:
      name: mariadb-server
      state: latest
    when: ansible_distribution in ["Ubuntu", "Debian"]

  - name: install mariadb Package (CentOS)
    tags: mariadb,centos,db
    dnf:
      name: mariadb
      state: latest
    when: ansible_distribution in ["CentOS"]

- hosts: file_servers
  become: true
  tasks:

  - name: install samba package
    tags: samba
    package:
      name: samba
      state: latest


