---

- hosts: all
  become: true
  pre_tasks:

  - name : install updates (CentOS)
    dnf:
      update_only: yes
      update_cache: yes
    when: ansible_distribution in ["CentOS"]

  - name : install updates (Ubuntu)
    apt:
      upgrade: dist
      update_cache: yes
    when: ansible_distribution in ["Ubuntu"]  

- hosts: web_servers
  become: true
  tasks:

  - name: install apache2 and php package for Debian
    apt:
      name:
        - apache2
        - libapache2-mod-php
      state: latest
    when: ansible_distribution in ["Ubuntu", "Debian"]

  - name: install httpd and php package for CentOS
    dnf:
      name: 
        - httpd
        - php
      state: latest
    when: ansible_distribution in ["CentOS"]

