- name: install apache2 and php package for Debian
  tags: apache,apache2,ubuntu
  apt:
    name:
      - apache2
      - libapache2-mod-php
    state: latest
  when: ansible_distribution in ["Ubuntu", "Debian"]

- name: install httpd and php package for CentOS
  tags: apache,httpd,centos
  dnf:
    name: 
      - httpd
      - php
    state: latest
  when: ansible_distribution in ["CentOS"]

- name: start httpd (CentOS)
  tags: apache,centos,httpd
  service:
    name: httpd
    state: started
    enabled: yes
  when: ansible_distribution in ["CentOS"]

- name: change e-mail address for admin
  tags: apache,centos,httpd
  lineinfile:
    path: /etc/httpd/conf/httpd.conf
    regexp: '^ServerAdmin'
    line: ServerAdmin somebody@email.example.com
  when: ansible_distribution in ["CentOS"]
  register: httpd

- name: FirewallD rules
  firewalld:
    permanent: yes
    immediate: yes
    service: "{{ item }}"
    state: enabled
  with_items:
    - http
    - https
  when: ansible_distribution in ["CentOS"]

- name: restart httpd (CentOS)
  tags: apache,centos,httpd
  service:
    name: httpd
    state: restarted
  when: httpd.changed

- name: copy default html to site
  tags: apache,apache2,httpd
  copy:
    src: default_site.html
    dest: /var/www/html/index.html
    owner: root
    group: root
    mode: 0644
