- name: add ssh key for philbot
  tags: always
  authorized_key:
    user: philbot
    key: "ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIOKNfldT/qKQzgZnE94pU0Gh0r+IUFerszq0uS2vv81L philbot"

- name: generate sshd from template
  tags: ssh
  template:
    src: "{{ ssh_template_file }}"
    dest: /etc/ssh/sshd_config
    owner: root
    group: root
    mode: 0644
  notify: restart_sshd 